export const constants = {
    Login:'Login',
    Login_Account: 'Login to your Account',
    Email: 'Email',
    Password: 'Password',
    getOtp: 'Get-Otp',
    ForgotPassword: 'Forgot the password?',
    SignUp: 'Sign Up',
    Create_Account: 'Create your Account',
    Phone: 'Phone',
    FirstName: 'First Name',
    LastName: 'Last Name',
    forgot: 'Select Which contact details should we use to reset your password',
    continue: 'Continue',
    verify: 'Verify',
    createPassword: 'Create Your New Password',
    salonOwer: 'Salon Owner',
    Next: 'Next',
    fillProfile: 'Fill Your Profile',
    salonTimeSloat: 'Salon Time Sloat',
    DayTime: 'Day Start Time',
    EndTime:'Day End Time',
    Lunch:'Pick your lunch time',
    Interval:'Interval',
    Max_Appointments:'Max Appointments'

}